### ISSUE TITLE
Update username error

### ISSUE THREAD

**Issue by garrylim** [garrylim/linkmein2.0#10]
![image](https://user-images.githubusercontent.com/40072417/204100366-7efcc1b4-a607-4fb6-b30e-26160df3204c.png)

for an example i swap my username to `garryxx` after i clicked submit turns out it gave an error

![image](https://user-images.githubusercontent.com/40072417/204100396-932fc692-aaac-4b17-9840-e63b3d6504a9.png)

**Comment by hadrihl** [comment]
This seems to be logical error.

whenever update username happened, it will execute post method controller `/update-profile`. No issue here as the user object will update to new username. 

```java
		@PostMapping("/update-profile")  
	    public String updateUserProfile(Model model, @ModelAttribute("user") User tmp, @RequestParam("id") Integer user_id) {
	        User user = userService.getUserById(user_id);
	        user.setUsername(tmp.getUsername());
	        user.setFirstname(tmp.getFirstname());
	        user.setLastname(tmp.getLastname());
	        user.setCompany(tmp.getCompany());
	        user.setCity(tmp.getCity());
	        user.setCountry(tmp.getCountry());

	        userService.saveUser(user);

	        return "redirect:dashboard";  //back to the page you want
	    }
```

Upon successful update username, system will call `/dashboard` controller. The error seem to trigger from this lines:

```java
User user = userService.getUserByUsername(loggedinUser.getUsername());
model.addAttribute("user_id", user.getId());
````

Username has changed. Current user who modify his username still loggedin in the system, therefore user object cannot be found because, current loggedin user still carry old-username, while new-username had been updated on the system(and db). 

we need a way to update user new-username to the loggedin user in the system. 

To fix this, Just add these lines:

```java
@PostMapping("/update-profile")  
	    public String updateUserProfile(Model model, @ModelAttribute("user") User tmp, @RequestParam("id") Integer user_id,
	    		**@AuthenticationPrincipal CustomUserDetails loggedinUser**) {
	        User user = userService.getUserById(user_id);
	        
	        user.setUsername(tmp.getUsername());
	        **loggedinUser.setUsername(tmp.getUsername());**
	        
	        user.setFirstname(tmp.getFirstname());
	        user.setLastname(tmp.getLastname());
	        user.setCompany(tmp.getCompany());
	        user.setCity(tmp.getCity());
	        user.setCountry(tmp.getCountry());

	        userService.saveUser(user);

	        return "redirect:dashboard";  //back to the page you want
	    }
```

Can try and see. No PR this time since it just casual and minor err. therefore hotfix is more suitable (rather than PR).

**Comment by garrylim** [comment]
Thx sir. The issue fixed ill update to my main here is the demo
![test2](https://user-images.githubusercontent.com/40072417/204199395-3fe016bd-f295-40ce-819b-1193494cd039.gif)

**Comment by garrylim** [comment]
issue solve closing issue now. :D
